// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use crate::{ffi,RepoInfo};
use glib::{translate::*};

glib::wrapper! {
    ///
    #[doc(alias = "ZyppRepository")]
    pub struct Repository(Object<ffi::ZyppRepository, ffi::ZyppRepositoryClass>);

    match fn {
        type_ => || ffi::zypp_repository_get_type(),
    }
}

impl Repository {
    ///
    /// # Returns
    ///
    /// Name of the repository
    #[doc(alias = "zypp_repository_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::zypp_repository_get_name(self.to_glib_none().0))
        }
    }

    ///
    /// # Returns
    ///
    /// The corresponding ZyppRepoInfo
    #[doc(alias = "zypp_repository_get_repoinfo")]
    #[doc(alias = "get_repoinfo")]
    pub fn repoinfo(&self) -> Option<RepoInfo> {
        unsafe {
            from_glib_full(ffi::zypp_repository_get_repoinfo(self.to_glib_none().0))
        }
    }
}
