// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct RepoManagerOptions(Boxed<ffi::ZyppRepoManagerOptions>);

    match fn {
        copy => |ptr| ffi::zypp_repo_manager_options_copy(mut_override(ptr)),
        free => |ptr| ffi::zypp_repo_manager_options_free(ptr),
        type_ => || ffi::zypp_repo_manager_options_get_type(),
    }
}

impl RepoManagerOptions {
    #[doc(alias = "zypp_repo_manager_options_new")]
    pub fn new(root: &str) -> RepoManagerOptions {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::zypp_repo_manager_options_new(root.to_glib_none().0))
        }
    }

    #[doc(alias = "zypp_repo_manager_options_get_root")]
    #[doc(alias = "get_root")]
    pub fn root(&mut self) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::zypp_repo_manager_options_get_root(self.to_glib_none_mut().0))
        }
    }
}
