// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use crate::{ffi,Context,InfoBase};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "ZyppServiceInfo")]
    pub struct ServiceInfo(Object<ffi::ZyppServiceInfo, ffi::ZyppServiceInfoClass>) @implements InfoBase;

    match fn {
        type_ => || ffi::zypp_service_info_get_type(),
    }
}

impl ServiceInfo {
    #[doc(alias = "zypp_service_info_new")]
    pub fn new(context: &Context) -> ServiceInfo {
        skip_assert_initialized!();
        unsafe {
            from_glib_full(ffi::zypp_service_info_new(context.to_glib_none().0))
        }
    }
}
