// Copyright (c) [2026] SUSE LLC
//
// All Rights Reserved.
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
// more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, contact SUSE LLC.
//
// To contact SUSE LLC about this file by physical or electronic mail, you may
// find current contact information at www.suse.com.

use agama_utils::api::ntp::{Config, Source, SourceType};
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("Failed to write configuration: {0}")]
    Io(#[from] std::io::Error),
    #[error("Failed to reload chronyd")]
    ReloadFailed,
}

const CHRONY_CONFIG_DIR: &str = "etc/chrony.d";
const CHRONY_CONFIG_FILE: &str = "99-agama.conf";
const DEFAULT_WORKDIR: &str = "/";
const DEFAULT_INSTALL_DIR: &str = "/mnt";

pub trait ModelAdapter: Send + 'static {
    fn write_config(&self, config: &Config) -> Result<(), Error>;
    fn install(&self, config: &Config) -> Result<(), Error>;
}

pub struct Model {
    workdir: PathBuf,
    install_dir: PathBuf,
}

impl Model {
    pub fn new() -> Self {
        Self {
            workdir: PathBuf::from(DEFAULT_WORKDIR),
            install_dir: PathBuf::from(DEFAULT_INSTALL_DIR),
        }
    }

    pub fn with_workdir<P: AsRef<Path>>(mut self, workdir: P) -> Self {
        self.workdir = PathBuf::from(workdir.as_ref());
        self
    }

    pub fn with_install_dir<P: AsRef<Path>>(mut self, install_dir: P) -> Self {
        self.install_dir = PathBuf::from(install_dir.as_ref());
        self
    }

    fn config_path(&self) -> PathBuf {
        self.workdir
            .join(CHRONY_CONFIG_DIR)
            .join(CHRONY_CONFIG_FILE)
    }

    fn install_config_path(&self) -> PathBuf {
        self.install_dir
            .join(CHRONY_CONFIG_DIR)
            .join(CHRONY_CONFIG_FILE)
    }

    fn reload_chrony(&self) -> Result<(), Error> {
        let output = Command::new("chronyc")
            .args(["reload", "sources"])
            .output();

        match output {
            Ok(result) => {
                if !result.status.success() {
                    let stderr = String::from_utf8_lossy(&result.stderr);
                    tracing::warn!("chronyc reload sources failed: {}", stderr);
                }
                Ok(())
            }
            Err(e) => {
                tracing::warn!("Failed to execute chronyc: {}", e);
                Ok(())
            }
        }
    }
}

impl Default for Model {
    fn default() -> Self {
        Self::new()
    }
}

impl ModelAdapter for Model {
    fn write_config(&self, config: &Config) -> Result<(), Error> {
        let path = self.config_path();

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let content = generate_chrony_config(config.sources.as_deref().unwrap_or(&[]));
        std::fs::write(&path, content)?;

        self.reload_chrony()?;
        Ok(())
    }

    fn install(&self, config: &Config) -> Result<(), Error> {
        let path = self.install_config_path();

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let content = generate_chrony_config(config.sources.as_deref().unwrap_or(&[]));
        std::fs::write(path, content)?;
        Ok(())
    }
}

fn generate_chrony_config(sources: &[Source]) -> String {
    let mut lines = vec!["# Generated by Agama".to_string()];

    for source in sources {
        let mut parts = vec![
            source_type_to_string(&source.source_type),
            source.address.clone(),
        ];

        if source.iburst {
            parts.push("iburst".to_string());
        }

        if source.offline {
            parts.push("offline".to_string());
        }

        lines.push(parts.join(" "));
    }

    lines.push(String::new());
    lines.join("\n")
}

fn source_type_to_string(source_type: &SourceType) -> String {
    match source_type {
        SourceType::Pool => "pool".to_string(),
        SourceType::Server => "server".to_string(),
        SourceType::Peer => "peer".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_chrony_config_empty() {
        let sources = vec![];
        let config = generate_chrony_config(&sources);
        assert_eq!(config, "# Generated by Agama\n");
    }

    #[test]
    fn test_generate_chrony_config_single_pool() {
        let sources = vec![Source {
            source_type: SourceType::Pool,
            address: "0.opensuse.pool.ntp.org".to_string(),
            iburst: true,
            offline: false,
        }];

        let config = generate_chrony_config(&sources);
        assert_eq!(
            config,
            "# Generated by Agama\npool 0.opensuse.pool.ntp.org iburst\n"
        );
    }

    #[test]
    fn test_generate_chrony_config_multiple_sources() {
        let sources = vec![
            Source {
                source_type: SourceType::Pool,
                address: "0.opensuse.pool.ntp.org".to_string(),
                iburst: true,
                offline: false,
            },
            Source {
                source_type: SourceType::Server,
                address: "ntp.example.com".to_string(),
                iburst: false,
                offline: true,
            },
            Source {
                source_type: SourceType::Peer,
                address: "ntp-peer.local".to_string(),
                iburst: false,
                offline: false,
            },
        ];

        let config = generate_chrony_config(&sources);
        let expected = "# Generated by Agama\n\
                        pool 0.opensuse.pool.ntp.org iburst\n\
                        server ntp.example.com offline\n\
                        peer ntp-peer.local\n";
        assert_eq!(config, expected);
    }

    #[test]
    fn test_model_write_config() {
        let tempdir = tempfile::tempdir().unwrap();
        let model = Model::new().with_workdir(tempdir.path());

        let config = Config {
            sources: Some(vec![Source {
                source_type: SourceType::Pool,
                address: "ntp.example.com".to_string(),
                iburst: true,
                offline: false,
            }]),
        };

        model.write_config(&config).unwrap();

        let written_path = tempdir.path().join(CHRONY_CONFIG_DIR).join(CHRONY_CONFIG_FILE);
        assert!(written_path.exists());

        let content = std::fs::read_to_string(&written_path).unwrap();
        assert!(content.contains("# Generated by Agama"));
        assert!(content.contains("pool ntp.example.com iburst"));
    }

    #[test]
    fn test_model_install() {
        let tempdir = tempfile::tempdir().unwrap();
        let model = Model::new().with_install_dir(tempdir.path());

        let config = Config {
            sources: Some(vec![Source {
                source_type: SourceType::Server,
                address: "ntp.server.com".to_string(),
                iburst: false,
                offline: true,
            }]),
        };

        model.install(&config).unwrap();

        let install_path = tempdir.path().join(CHRONY_CONFIG_DIR).join(CHRONY_CONFIG_FILE);
        assert!(install_path.exists());

        let content = std::fs::read_to_string(&install_path).unwrap();
        assert!(content.contains("server ntp.server.com offline"));
    }
}
