# frozen_string_literal: true

# Copyright (c) [2024-2026] SUSE LLC
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, contact SUSE LLC.
#
# To contact SUSE LLC about this file by physical or electronic mail, you may
# find current contact information at www.suse.com.

require "agama/storage/proposal_strategies/base"
require "agama/storage/proposal_settings"
require "agama/storage/proposal_settings_reader"
require "agama/storage/bootloader_config_solver"

module Agama
  module Storage
    module ProposalStrategies
      # Strategy used by the Agama proposal for backwards compatibility with AutoYaST.
      class Autoyast < Base
        include Yast::I18n

        # @param product_config [Config] Product config
        # @param storage_system [Storage::System]
        # @param partitioning [Array<Hash>]
        # @param bootloader_config [Agama::Storage::BootloaderConfig]
        # @param logger [Logger]
        def initialize(product_config, storage_system, partitioning, bootloader_config, logger)
          textdomain "agama"

          super(product_config, storage_system, bootloader_config, logger)
          @partitioning = partitioning
        end

        # Settings used for calculating the proposal.
        #
        # @return [Array<Hash>]
        attr_reader :partitioning
        alias_method :settings, :partitioning

        # @see Base#calculate
        def calculate
          @ay_issues = ::Installation::AutoinstIssues::List.new
          disable_bls_bootloader
          proposal = Y2Storage::AutoinstProposal.new(
            partitioning:      partitioning,
            proposal_settings: proposal_settings,
            devicegraph:       storage_system.devicegraph,
            disk_analyzer:     storage_system.analyzer,
            issues_list:       ay_issues
          )
          proposal.propose
          log_warnings
        ensure
          storage_manager.proposal = proposal
        end

        # @see Base#issues
        def issues
          ay_errors.map { |i| agama_issue(i) }
        end

      private

        # Issues generated by the AutoYaST proposal
        # @return [::Installation::AutoinstIssues::List]
        attr_reader :ay_issues

        # Default proposal settings, potentially used to calculate omitted information
        #
        # @return [Y2Storage::ProposalSettings]
        def proposal_settings
          agama_default = ProposalSettingsReader.new(product_config).read
          root_vol = agama_default.volumes.find { |v| v.mount_path == "/" }
          if root_vol&.btrfs
            root_vol.btrfs.subvolumes.concat(bootloader_config.type.root_subvolumes)
          end
          agama_default.to_y2storage(config: product_config, bootloader_config: bootloader_config)
        end

        # Logs AutoYaST warnings
        def log_warnings
          ay_warnings.each { |w| logger.warn(w) }
        end

        # AutoYaST warnings
        #
        # @return [Array<::Installation::AutoinstIssues::Issue>
        def ay_warnings
          ay_issues.select(&:warn?)
        end

        # AutoYaST errors
        #
        # @return [Array<::Installation::AutoinstIssues::Issue>
        def ay_errors
          ay_issues.reject(&:warn?)
        end

        # Agama issue equivalent to the given AutoYaST issue
        def agama_issue(ay_issue)
          Issue.new(ay_issue.message)
        end

        # The underlying yast-storage-ng contains its own logic to infer which boot loader will
        # be used when deciding the strategy to calculate boot partitions. This method tries to
        # influence that logic in order to get a proposal that is aligned with the rest of the
        # Agama settings.
        #
        # TODO: there is no way to actually enable a BLS-based bootloader if the product is
        # configured in YaST to never use that kind of bootloaders. The plan is to re-evaluate the
        # changes needed in Y2Storage::BootRequirementsChecker in the short future.
        def disable_bls_bootloader
          BootloaderConfigSolver.new(product_config).solve(@bootloader_config)
          value = @bootloader_config.type == Y2Storage::BootloaderType::GRUB2 ? "1" : "0"
          ENV["YAST_NO_BLS_BOOT"] = value
          # Avoiding problems with cached values
          Y2Storage::StorageEnv.instance.reset_cache
        end
      end
    end
  end
end
