# frozen_string_literal: true

source "https://rubygems.org"

gem "eventmachine"
gem "em-websocket"
gem "rack-contrib", require: "rack/contrib"
gem "rake"
gem "sinatra"
gem "sinatra-cors"
gem "ruby-dbus", require: "dbus"
gem "thin"
gem "rexml" # ruby3 has it as separate gem
