# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# vendor is not controlled by us and y2dir is often modified old yast code that
# we do not want to rewrite now
AllCops:
  Exclude:
    - vendor/**/*
    - lib/agama/dbus/y2dir/**/*
    - agama-yast.gemspec
    - package/*.spec

# a D-Bus method definition may take up more line length than usual
Layout/LineLength:
  IgnoredPatterns:
    - dbus_method

# a D-Bus interface definition may take up more lines than a regular method
Metrics/BlockLength:
  IgnoredMethods:
    - dbus_interface

# assignment in method calls is used to document some params
Lint/UselessAssignment:
  Enabled: false

# be less strict
Metrics/AbcSize:
  Max: 32

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - lib/agama/software/repository.rb

Metrics/ClassLength:
  # lib/agama/registration.rb is the outlier that should be split up
  Max: 306
