# frozen_string_literal: true

# just inherit the usual YaST rake tasks
require "yast/rake"

Yast::Tasks.configuration do |conf|
  # lets ignore license check for now
  conf.skip_license_check << /.*/
end
