/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BootloaderType = "grub2" | "grub2-bls" | "systemd-boot";
export type EncryptionAuthMethod = "password" | "tpm";

/**
 * API description of the bootloader system
 */
export interface System {
  /**
   * Possible bootloaders to select in the current system.
   */
  availableBootloaders: Bootloader[];
}
export interface Bootloader {
  type: BootloaderType;
  /**
   * Encryption authentication methods that can be managed by the bootloader in this system.
   */
  encryptionAuth: EncryptionAuthMethod[];
}
