/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * API description of the iSCSI system
 */
export interface System {
  initiator: Initiator;
  targets: Target[];
}
export interface Initiator {
  name: string;
  ibft: boolean;
}
export interface Target {
  name: string;
  address: string;
  port: number;
  interface: string;
  /**
   * Whether the target was initiated by iBFT.
   */
  ibtf: boolean;
  startup: "onboot" | "manual" | "automatic";
  /**
   * Whether the node is connected (there is a session).
   */
  connected: boolean;
  /**
   * Whether the node is locked (cannot be deactivated)
   */
  locked: boolean;
}
