/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * API description of the zFCP system
 */
export interface System {
  /**
   * Whether automatic LUN scan is active in the system.
   */
  lunScan: boolean;
  /**
   * zFCP controllers
   */
  controllers: Controller[];
  /**
   * zFCP devices
   */
  devices: Device[];
}
export interface Controller {
  channel: string;
  /**
   * All available WWPNs.
   */
  wwpns: string[];
  /**
   * Whether the controller automatically scans LUNs.
   */
  lunScan: boolean;
  active: boolean;
}
export interface Device {
  channel: string;
  wwpn: string;
  lun: string;
  active: boolean;
  /**
   * Device name assigned by the kernel once it is active.
   */
  deviceName?: string;
}
