/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FilesystemType =
  | "bcachefs"
  | "btrfs"
  | "exfat"
  | "ext2"
  | "ext3"
  | "ext4"
  | "f2fs"
  | "jfs"
  | "nfs"
  | "nilfs2"
  | "ntfs"
  | "reiserfs"
  | "swap"
  | "tmpfs"
  | "vfat"
  | "xfs";
export type SpacePolicy = "delete" | "resize" | "keep" | "custom";
export type Boot = "implicit" | "explicit";
export type PtableType = "gpt" | "msdos" | "dasd";
export type PartitionId = "linux" | "swap" | "lvm" | "raid" | "esp" | "prep" | "bios_boot";

/**
 * Config model
 */
export interface Config {
  drives?: Drive[];
  volumeGroups?: VolumeGroup[];
}
export interface Drive {
  name: string;
  alias?: string;
  mountPath?: string;
  filesystem?: Filesystem;
  boot?: Boot;
  volumeGroups?: string[];
  spacePolicy?: SpacePolicy;
  ptableType?: PtableType;
  partitions?: Partition[];
}
export interface VolumeGroup {
  name: string;
}
export interface Filesystem {
  default: boolean;
  type?: FilesystemType;
  snapshots?: boolean;
}
export interface Partition {
  name?: string;
  alias?: string;
  id?: PartitionId;
  mountPath?: string;
  filesystem?: Filesystem;
  size?: Size;
  delete?: boolean;
  deleteIfNeeded?: boolean;
  resize?: boolean;
  resizeIfNeeded?: boolean;
}
export interface Size {
  default: boolean;
  min: number;
  max?: number;
}
