# frozen_string_literal: true

source "https://rubygems.org"

gem "rake"
gem "ruby-dbus"
gem "eventmachine"
gem "nokogiri"

# Required by YaST
gem "cheetah"
gem "fast_gettext"
gem "nokogiri"
gem "cfa"
gem "cfa_grub2"
