/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ListOfUserSelectedPatternsToInstall = string[];
export type ListOfUserSelectedPatternsToAddToTheList = string[];
export type ListOfUserSelectedPatternsToRemoveFromTheList = string[];
export type ListOfPackagesToInstall = string[];
export type FlagIfOnlyMinimalHardDependenciesShouldBeUsedInSolver = boolean;
export type AliasUsedForRepositoryActingAsIdentifier = string;
export type URLPointingToRepository = string;
export type RepositoryPriority = number;
export type UserVisibleNameDefaultsToAlias = string;
export type ProductDirectoryOnMultiRepoDVDUsuallyNotNeeded = string;
export type IfRepositoryShouldBeEnabledDefaultsToTrueUsefulWhenAddingAdditionalRepoThatShouldNotBeImmediatelyUse =
  boolean;
export type IfUnsignedRepositoriesAreAllowedMainlyUsefulForRepositoriesThatIsHandCraftedWithoutGPGSignature = boolean;
export type ListOfGPGFingerprintsThatIsAcceptedForThisRepositoryUsefulForOwnRepositoriesWithProperGPGSignature =
  string[];
export type ListOfUserSpecifiedRepositoriesThatWillBeUsedOnTopOfDefaultOnes = PackagesRepository[];

/**
 * Software configuration.
 */
export interface Config {
  patterns?: ListOfUserSelectedPatternsToInstall | ModificationsForTheListOfUserSelectedPatternsToInstall;
  packages?: ListOfPackagesToInstall;
  onlyRequired?: FlagIfOnlyMinimalHardDependenciesShouldBeUsedInSolver;
  extraRepositories?: ListOfUserSpecifiedRepositoriesThatWillBeUsedOnTopOfDefaultOnes;
  [k: string]: unknown;
}
export interface ModificationsForTheListOfUserSelectedPatternsToInstall {
  add?: ListOfUserSelectedPatternsToAddToTheList;
  remove?: ListOfUserSelectedPatternsToRemoveFromTheList;
}
export interface PackagesRepository {
  alias?: AliasUsedForRepositoryActingAsIdentifier;
  url?: URLPointingToRepository;
  priority?: RepositoryPriority;
  name?: UserVisibleNameDefaultsToAlias;
  productDir?: ProductDirectoryOnMultiRepoDVDUsuallyNotNeeded;
  enabled?: IfRepositoryShouldBeEnabledDefaultsToTrueUsefulWhenAddingAdditionalRepoThatShouldNotBeImmediatelyUse;
  allowUnsigned?: IfUnsignedRepositoriesAreAllowedMainlyUsefulForRepositoriesThatIsHandCraftedWithoutGPGSignature;
  gpgFingerprints?: ListOfGPGFingerprintsThatIsAcceptedForThisRepositoryUsefulForOwnRepositoriesWithProperGPGSignature;
}
