// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ZyppContextClass", sizeof(ZyppContextClass), alignof(ZyppContextClass));
    printf("%s;%zu;%zu\n", "ZyppException", sizeof(ZyppException), alignof(ZyppException));
    printf("%s;%zu;%zu\n", "ZyppExpectedClass", sizeof(ZyppExpectedClass), alignof(ZyppExpectedClass));
    printf("%s;%zu;%zu\n", "ZyppInfoBaseInterface", sizeof(ZyppInfoBaseInterface), alignof(ZyppInfoBaseInterface));
    printf("%s;%zu;%zu\n", "ZyppProgressObserverClass", sizeof(ZyppProgressObserverClass), alignof(ZyppProgressObserverClass));
    printf("%s;%zu;%zu\n", "ZyppRepoInfoClass", sizeof(ZyppRepoInfoClass), alignof(ZyppRepoInfoClass));
    printf("%s;%zu;%zu\n", "ZyppRepoInfoType", sizeof(ZyppRepoInfoType), alignof(ZyppRepoInfoType));
    printf("%s;%zu;%zu\n", "ZyppRepoManagerClass", sizeof(ZyppRepoManagerClass), alignof(ZyppRepoManagerClass));
    printf("%s;%zu;%zu\n", "ZyppRepoManagerError", sizeof(ZyppRepoManagerError), alignof(ZyppRepoManagerError));
    printf("%s;%zu;%zu\n", "ZyppRepoRefreshResult", sizeof(ZyppRepoRefreshResult), alignof(ZyppRepoRefreshResult));
    printf("%s;%zu;%zu\n", "ZyppRepositoryClass", sizeof(ZyppRepositoryClass), alignof(ZyppRepositoryClass));
    printf("%s;%zu;%zu\n", "ZyppServiceInfoClass", sizeof(ZyppServiceInfoClass), alignof(ZyppServiceInfoClass));
    return 0;
}
