[Service]
# We have to explicitly clear ExecStart which (most probably)
# exists in the original service file. If not systemd will try
# to start every ExecStart (original even the one added bellow)
ExecStart=
ExecStart=/root/.local/bin/gnome-kiosk-wrapper
