/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DeviceClass = "drive" | "mdRaid" | "partition" | "volumeGroup" | "logicalVolume";
export type DriveType = "disk" | "raid" | "multipath" | "dasd";
export type FilesystemType =
  | "bcachefs"
  | "btrfs"
  | "exfat"
  | "ext2"
  | "ext3"
  | "ext4"
  | "f2fs"
  | "jfs"
  | "nfs"
  | "nilfs2"
  | "ntfs"
  | "reiserfs"
  | "swap"
  | "tmpfs"
  | "vfat"
  | "xfs";
export type MDLevel = "raid0" | "raid1" | "raid5" | "raid6" | "raid10";
export type PartitionTableType = "gpt" | "msdos" | "dasd";

/**
 * API description of the storage proposal.
 */
export interface Proposal {
  /**
   * Expected layout of the system after the commit phase.
   */
  devices?: Device[];
  /**
   * Sorted list of actions to execute during the commit phase.
   */
  actions?: Action[];
}
/**
 * Schema to describe a device both in 'system' and 'proposal'.
 */
export interface Device {
  sid: number;
  name: string;
  description?: string;
  class?: DeviceClass;
  block?: Block;
  drive?: Drive;
  filesystem?: Filesystem;
  md?: Md;
  multipath?: Multipath;
  partitionTable?: PartitionTable;
  partition?: Partition;
  partitions?: Device[];
  volumeGroup?: VolumeGroup;
  logicalVolumes?: Device[];
}
export interface Block {
  start: number;
  size: number;
  active?: boolean;
  encrypted?: boolean;
  udevIds?: string[];
  udevPaths?: string[];
  systems?: string[];
  shrinking: ShrinkInfo;
}
export interface ShrinkInfo {
  supported: boolean;
  minSize?: number;
  reasons?: string[];
}
export interface Drive {
  type?: DriveType;
  vendor?: string;
  model?: string;
  transport?: string;
  bus?: string;
  busId?: string;
  driver?: string[];
  info?: DriveInfo;
}
export interface DriveInfo {
  sdCard?: boolean;
  dellBoss?: boolean;
}
export interface Filesystem {
  sid: number;
  type: FilesystemType;
  mountPath?: string;
  label?: string;
}
export interface Md {
  level: MDLevel;
  devices: number[];
  uuid?: string;
}
export interface Multipath {
  wireNames: string[];
}
export interface PartitionTable {
  type: PartitionTableType;
  unusedSlots: UnusedSlot[];
}
export interface UnusedSlot {
  start: number;
  size: number;
}
export interface Partition {
  efi: boolean;
}
export interface VolumeGroup {
  size: number;
  physicalVolumes: number[];
}
export interface Action {
  device: number;
  text: string;
  subvol?: boolean;
  delete?: boolean;
  resize?: boolean;
}
