//! # D-Bus interface proxy for: `org.opensuse.Agama.Storage1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `storage.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    default_service = "org.opensuse.Agama.Storage1",
    default_path = "/org/opensuse/Agama/Storage1",
    interface = "org.opensuse.Agama.Storage1",
    assume_defaults = true
)]
pub trait Storage1 {
    /// Activate method
    fn activate(&self) -> zbus::Result<()>;

    /// Finish method
    fn finish(&self) -> zbus::Result<()>;

    /// GetConfigFromModel method
    fn get_config_from_model(&self, model: &str) -> zbus::Result<String>;

    /// Install method
    fn install(&self) -> zbus::Result<()>;

    /// Probe method
    fn probe(&self) -> zbus::Result<()>;

    /// SetConfig method
    fn set_config(&self, product: &str, config: &str) -> zbus::Result<()>;

    /// SetLocale method
    fn set_locale(&self, locale: &str) -> zbus::Result<()>;

    /// SolveConfigModel method
    fn solve_config_model(&self, model: &str) -> zbus::Result<String>;

    /// Umount method
    fn umount(&self) -> zbus::Result<()>;

    /// ProgressChanged signal
    #[zbus(signal)]
    fn progress_changed(&self, progress: &str) -> zbus::Result<()>;

    /// ProgressFinished signal
    #[zbus(signal)]
    fn progress_finished(&self) -> zbus::Result<()>;

    /// Config property
    #[zbus(property)]
    fn config(&self) -> zbus::Result<String>;

    /// ConfigModel property
    #[zbus(property)]
    fn config_model(&self) -> zbus::Result<String>;

    /// Issues property
    #[zbus(property)]
    fn issues(&self) -> zbus::Result<String>;

    /// Proposal property
    #[zbus(property)]
    fn proposal(&self) -> zbus::Result<String>;

    /// System property
    #[zbus(property)]
    fn system(&self) -> zbus::Result<String>;
}
