/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MDLevel = "raid0" | "raid1" | "raid5" | "raid6" | "raid10";

/**
 * API description of the system
 */
export interface System {
  /**
   * All relevant devices on the system
   */
  devices?: StorageDevice[];
  /**
   * SIDs of the available drives
   */
  availableDrives?: number[];
  /**
   * SIDs of the available MD RAIDs
   */
  availableMdRaids?: number[];
  /**
   * SIDs of the drives that are candidate for installation
   */
  candidateDrives?: number[];
  /**
   * SIDs of the MD RAIDs that are candidate for installation
   */
  candidateMdRaids?: number[];
  /**
   * Meaningful mount points for the current product
   */
  productMountPoints?: string[];
  /**
   * Possible encryption methods for the current system and product
   */
  encryptionMethods?: (
    | "luks1"
    | "luks2"
    | "pervasiveLuks2"
    | "tmpFde"
    | "protectedSwap"
    | "secureSwap"
    | "randomSwap"
  )[];
  /**
   * Volumes defined by the product as templates
   */
  volumeTemplates?: Volume[];
  issues?: Issue[];
}
/**
 * Schema to describe a device both in 'system' and 'proposal'.
 */
export interface StorageDevice {
  sid: number;
  name: string;
  description?: string;
  block?: Block;
  drive?: Drive;
  filesystem?: Filesystem;
  md?: Md;
  multipath?: Multipath;
  partitionTable?: PartitionTable;
  partition?: Partition;
  partitions?: StorageDevice[];
  volumeGroup?: VolumeGroup;
  logicalVolumes?: StorageDevice[];
}
export interface Block {
  start: number;
  size: number;
  active?: boolean;
  encrypted?: boolean;
  udevIds?: string[];
  udevPaths?: string[];
  systems?: string[];
  shrinking: ShrinkingSupported | ShrinkingUnsupported;
}
export interface ShrinkingSupported {
  supported?: number;
}
export interface ShrinkingUnsupported {
  unsupported?: string[];
}
export interface Drive {
  type?: "disk" | "raid" | "multipath" | "dasd";
  vendor?: string;
  model?: string;
  transport?: string;
  bus?: string;
  busId?: string;
  driver?: string[];
  info?: DriveInfo;
}
export interface DriveInfo {
  sdCard?: boolean;
  dellBoss?: boolean;
}
export interface Filesystem {
  sid: number;
  type:
    | "bcachefs"
    | "btrfs"
    | "exfat"
    | "ext2"
    | "ext3"
    | "ext4"
    | "f2fs"
    | "jfs"
    | "nfs"
    | "nilfs2"
    | "ntfs"
    | "reiserfs"
    | "swap"
    | "tmpfs"
    | "vfat"
    | "xfs";
  mountPath?: string;
  label?: string;
}
export interface Md {
  level: MDLevel;
  devices: number[];
  uuid?: string;
}
export interface Multipath {
  wireNames: string[];
}
export interface PartitionTable {
  type: "gpt" | "msdos" | "dasd";
  unusedSlots: number[][];
}
export interface Partition {
  efi: boolean;
}
export interface VolumeGroup {
  size: number;
  physicalVolumes: number[];
}
export interface Volume {
  mountPath: string;
  mountOptions?: string[];
  fsType?:
    | "bcachefs"
    | "btrfs"
    | "exfat"
    | "ext2"
    | "ext3"
    | "ext4"
    | "f2fs"
    | "jfs"
    | "nfs"
    | "nilfs2"
    | "ntfs"
    | "reiserfs"
    | "swap"
    | "tmpfs"
    | "vfat"
    | "xfs";
  autoSize: boolean;
  minSize: number;
  maxSize?: number;
  snapshots?: boolean;
  transactional?: boolean;
  outline?: VolumeOutline;
}
export interface VolumeOutline {
  required: boolean;
  supportAutoSize: boolean;
  fsTypes?: (
    | "bcachefs"
    | "btrfs"
    | "exfat"
    | "ext2"
    | "ext3"
    | "ext4"
    | "f2fs"
    | "jfs"
    | "nfs"
    | "nilfs2"
    | "ntfs"
    | "reiserfs"
    | "swap"
    | "tmpfs"
    | "vfat"
    | "xfs"
  )[];
  adjustByRam?: boolean;
  snapshotsConfigurable?: boolean;
  snapshotsAffectSizes?: boolean;
  sizeRelevantVolumes?: string[];
}
export interface Issue {
  description: string;
  class?: string;
  details?: string;
  source?: "config" | "system";
  severity?: "warn" | "error";
}
