//! # D-Bus interface proxy for: `org.opensuse.Agama.Storage1.ISCSI`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `iscsi.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    default_service = "org.opensuse.Agama.Storage1",
    default_path = "/org/opensuse/Agama/Storage1/ISCSI",
    interface = "org.opensuse.Agama.Storage1.ISCSI",
    assume_defaults = true
)]
pub trait ISCSI {
    /// Discover method
    fn discover(&self, serialized_options: &str) -> zbus::Result<u32>;

    /// GetConfig method
    fn get_config(&self) -> zbus::Result<String>;

    /// GetSystem method
    fn get_system(&self) -> zbus::Result<String>;

    /// SetConfig method
    fn set_config(&self, serialized_config: &str) -> zbus::Result<()>;

    /// ProgressChanged signal
    #[zbus(signal)]
    fn progress_changed(&self, progress: &str) -> zbus::Result<()>;

    /// ProgressFinished signal
    #[zbus(signal)]
    fn progress_finished(&self) -> zbus::Result<()>;

    /// SystemChanged signal
    #[zbus(signal)]
    fn system_changed(&self, system: &str) -> zbus::Result<()>;
}
