# This is a helper action for debugging the conditions used for starting the
# automatic OBS submission.

# See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions

name: Debug obs2branch

permissions:
  contents: read

on:
  push:

  # allow running manually
  workflow_dispatch:

env:
  obs_project: ${{ fromJson(vars.OBS_PROJECTS)[github.ref_name] }}

jobs:
  test:

    if: "!github.event.repository.fork"

    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo 'Current GitHub Action variables and values:'
          echo 'vars.OBS_USER: ${{ vars.OBS_USER }}'
          echo 'vars.OBS_PROJECTS: ${{ vars.OBS_PROJECTS }}'
          echo 'parsed vars.OBS_PROJECTS: ${{ fromJson(vars.OBS_PROJECTS) }}'
          echo 'github.ref_name: ${{ github.ref_name }}'
          echo 'Target OBS project: ${{ env.obs_project }}'
          echo 'Submit condition: ${{ vars.OBS_PROJECTS && env.obs_project && vars.OBS_USER }}'
          echo 'Submit would start: ${{ !!(vars.OBS_PROJECTS && env.obs_project && vars.OBS_USER) }}'
