# This is a helper action for debugging the conditions used for starting the
# automatic OBS submission.

# See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions

name: Debug obs2branch

permissions:
  contents: read

on:
  push:

  # allow running manually
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo 'Current GitHub Action variables and values:'
          echo 'vars.OBS_USER: ${{ vars.OBS_USER }}'
          echo 'vars.OBS_PROJECTS: ${{ vars.OBS_PROJECTS }}'
          echo 'parsed vars.OBS_PROJECTS: ${{ fromJson(vars.OBS_PROJECTS) }}'
          echo 'github.ref_name: ${{ github.ref_name }}'
          echo 'Target OBS project: ${{ fromJson(vars.OBS_PROJECTS)[github.ref_name] }}'
          echo 'Submit condition: ${{ vars.OBS_PROJECTS && fromJson(vars.OBS_PROJECTS)[github.ref_name] && vars.OBS_USER }}'
          echo 'Submit would start: ${{ !contains(fromJSON('[false, 0, -0, "", null]'), vars.OBS_PROJECTS && fromJson(vars.OBS_PROJECTS)[github.ref_name] && vars.OBS_USER) }}'

