#! /bin/sh

# This script builds the POT file with the translatable texts from the web UI.
# It runs xgettext in  a container so it works also in systems with older
# gettext which does not support the TSX input format.

# path to this script
DIR="$(dirname "$0")"

# build the container if it does not exist yet, if it exists it just reuses the cached image
"$DIR"/../devel/xgettext/build.sh

# the target file
OUTPUT="${1:-agama.pot}"
# run the container script instead of the standard "xgettext" command
XGETTEXT="$DIR"/../devel/xgettext/xgettext.sh

"$DIR"/build_pot "$OUTPUT" "$XGETTEXT"
